version: '3'

services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
     - NODE_ENV=production
     - PORT=3000

  frontend:
    container_name: frontend
    image: nginx
    volumes:
      - ./client/build:/usr/share/nginx/html
    ports:
      - "8080:80" # Forward site to localhost:8080
  redis:
    container_name: redis
    image: redis:4
    ports:
      - "6379:6379"
